# Generated by Django 5.0.11 on 2025-02-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_product_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='image',
        ),
    ]
