# Generated by Django 5.0.11 on 2025-02-05 19:34

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_link_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=models.URLField(blank=True, max_length=500, validators=[shop.models.validate_image_url])),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
